### ISSUE TITLE
Update terraform 0.12

### ISSUE THREAD

**Issue by nicobrinkkemper** [SweetOps/terraform-google-service-account#7]
I'm seeing,
```
Error: Invalid function argument

  on .terraform/modules/s3_service_account.label/main.tf line 81, in locals:
  81:     attributes  = "${lower(join(local.delimiter, local.attributes))}"
    |----------------
    | local.attributes is tuple with 1 element

Invalid value for "lists" parameter: element 0: string required.
```
when following the example

**Comment by nicobrinkkemper** [comment]
Working fork: 
https://github.com/nicobrinkkemper/terraform-google-service-account

**Comment by khalidid** [comment]
Hello nicobrinkkemper

I have the same error for bucker project (sweeOps), how do you resolve it ?

thanks

**Comment by SweetOps** [comment]
https://github.com/SweetOps/terraform-google-service-account/pull/8

**Comment by SweetOps** [comment]
has been fixed in the new module version https://github.com/SweetOps/terraform-google-service-account/releases/tag/0.3.0
